name: Build sitio web

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Mostrar archivos
        run: |
          ls -la
          echo " Build simulado completo"
